import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Notification from "./_components/notification";
import NotifProvider from "./_lib/context/notifContext"; 
import QueryProvider from '@/_lib/providers/QueryProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <NotifProvider>
    <QueryProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-dvh relative no-text-cursor no-text-select min-h-0 min-w-0`}
        >
        <Notification />
        {children}
      </body>
    </html>
    </QueryProvider>
    </NotifProvider>
  );
}
